#ifndef MAIN_CONFIG_H_
#define MAIN_CONFIG_H_

#define APP_NAME "EvLamp"

#define TAG APP_NAME

#ifdef CONFIG_EL_WIFI_MODE_AP
#define DEFAULT_WIFI_MODE WIFI_MODE_AP
#else
#define DEFAULT_WIFI_MODE WIFI_MODE_STA
#endif

#if CONFIG_EL_WIFI_DHCP
#define DEFAULT_WIFI_DHCP true
#else
#define DEFAULT_WIFI_DHCP false
#endif

#define DEFAULT_WIFI_AP_MAXCONN 5

#define BUS_QUEUE_LEN 5
#define BUS_TIMEOUT_MS 500

#define MAIN_TASK_STACK_SIZE 8192
#define MAIN_TASK_PRIORITY 5

#if CONFIG_EL_LED_TYPE_APA106
#define DEFAULT_LED_TYPE LED_STRIP_APA106
#elif CONFIG_EL_LED_TYPE_SK6812
#define DEFAULT_LED_TYPE LED_STRIP_SK6812
#else
#define DEFAULT_LED_TYPE LED_STRIP_WS2812
#endif

#define LED_STRIP_RMT_CHANNEL RMT_CHANNEL_0
#define SINGLE_LED_CURRENT_MA 60.0f

#define FPS_MAX 120

#endif /* MAIN_CONFIG_H_ */
